# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b2ae87a130e8f54fa2574f1355c86765427dd914255825db76d46f0f19e89b97fb3dc8930bd0c849e3d909bab7174dcad29056553271a60f4eb2805380dc4cfd

test:
  secret_key_base: 425292aa009f238045437ed80b7bb5a30189ef5f4a7751a8eabb863723cf35a9b3d333f30ee16dd441d933165a18df0c8002721c1e0bb7ceaade17d894b0f7cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
